[package]
name = "kalkulator_do_szkol_sredniej"
version = "0.1.0"
edition = "2021"

[package.metadata.android]
res = "android_res"
icon = "@mipmap/skm_launcher"
[package.metadata.android.activity_attributes]
"android:exported" =  "true"
"android:screenOrientation" = "userLandscape"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
